language: node_js
node_js: node
script: npm run production
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAIOKDZBTPFESKVC3Q
  secret_access_key:
    secure: jiTx4WGUGYsq3Ar4ZHlGU0HosNK6KkNK99Uohj6kpvenciLX9Xs9cRnEBWdeu4BruYp6oqsMpmeV4oQyudxCzn6hBCpz+Qa6zB04e4g15iUtUmF9HRGEFTE2Be4VTu0Tln3YEUFONiKFAKRClNdaaNC6LrZOrYR9p55J1DOh32HYQsFrXWqiS54hWk+wVdJPaz1BjWWrj2BNgvNK1DqJhor5tNrZzeSDVCaPb3/RG3UjGCJHuk1CgWP2Mv0AYR/MK7wjoUYovNdMJOpOkqoTCRP+9Pn5ZUM6tHJ0EsSdmRsPPdxkai398vlxHcoj4b1JGEAFTHHCfoYxxG6pS/pQ0/jMz8aHbIWfCLUDAcTwF+xhqpxyr4AzNPfpLLbVIXkMBbgc7Wv+G5uN37UfgNXU5aC2Qd/hSrRH1ey3e0eNCD5lHAUChA6xErA1l95+garQZEXe1/CazXgAL7uDERLqHhwyYTsdYerdLUZk23ySOjSpTxqXPV3oKsCj9OlnfXrynqFJHuAq1D5YW1pYhAUJ2FcwHWSYVMTe5e96ogLvmSenDqo2C+bRhzAuKFKO5ujrgjQN/91ao85OUPcKM9vdW7FxoxUGeykqluJBCw36E0yAY33uVsWQ1kzOknWpgOc5eLYWXLrlgii+j1gQtGfzu5WiaYhInCq1SL4oqLJe6No=
  bucket: aws-website-cardinal-gxchj
  skip_cleanup: true
  acl: public_read
  local_dir: production
  on:
    repo: mpiroc/cardinal
    branch: staging
